[gcp_service_account]
type = "service_account"
project_id = "finance-streamlit-app-495108"
private_key_id = "d08d256feab6cf6a53bdcc82b65c038b018cc07b"
private_key = "-----BEGIN PRIVATE KEY-----\nPASTE_YOUR_LONG_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-financedash-drive-re@finance-streamlit-app-495108.iam.gserviceaccount.com"
client_id = "PASTE_YOUR_CLIENT_ID_HERE"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-financedash-drive-re%40finance-streamlit-app-495108.iam.gserviceaccount.com"
